
namespace GameSeat.Backend.Infrastructure.Data.Models
{
    public class UserModel
    {

        public int Id { get; set; } // Identity generated by the DB
        public string Username { get; set; } = string.Empty; // Valor predeterminado seguro para una propiedad requerida
        public string Email { get; set; } = string.Empty;
        public bool Admin { get; set; } = false; // Valor predeterminado
        public bool Enable { get; set; } = true; // Valor predeterminado
        public int Image { get; set; } = 1;

        // Constructor vacío
        public UserModel() {}

    }
}
